version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./applications:/var/www/html
      - ./storage:/var/www/storage
    environment:
      - APP_ENV=production
    depends_on:
      - redis
      - database

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: zeropay
      POSTGRES_USER: zeropay
      POSTGRES_PASSWORD: secure_password
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  redis-data:
  db-data:
