version: '3.9'

services:
  # Monolith Application
  app:
    build:
      context: ./core/monolith
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./core/monolith:/var/www/html
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - REDIS_HOST=redis
    depends_on:
      - postgres
      - redis

  # API Gateway
  api-gateway:
    build:
      context: ./core/microservices/api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - app

  # Web Application
  web:
    build:
      context: ./applications/web
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://api-gateway:3000

  # Databases
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: smartautoparts
      POSTGRES_USER: sauser
      POSTGRES_PASSWORD: sapass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  # ElasticSearch
  elasticsearch:
    image: elasticsearch:8.11.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - elastic_data:/usr/share/elasticsearch/data

volumes:
  postgres_data:
  redis_data:
  elastic_data:
