global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3000']
  
  - job_name: 'microservices'
    static_configs:
      - targets: 
        - 'product-service:3002'
        - 'order-service:3003'
        - 'payment-service:3004'
        - 'ai-service:3005'
  
  - job_name: 'databases'
    static_configs:
      - targets: 
        - 'postgres-exporter:9187'
        - 'redis-exporter:9121'
